"""empty message

Revision ID: 0ba298a3d352
Revises: e5abdcf5a095
Create Date: 2019-01-15 22:27:27.815383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ba298a3d352'
down_revision = 'e5abdcf5a095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('status', mysql.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
