"""empty message

Revision ID: 0efc1fed2efa
Revises: 8b64d25b899e
Create Date: 2019-01-18 00:49:55.323191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0efc1fed2efa'
down_revision = '8b64d25b899e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'task_status', ['task_status_id'], ['task_status_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'task_status_id')
    # ### end Alembic commands ###
