"""empty message

Revision ID: 6a6489f0a40e
Revises: 
Create Date: 2019-01-07 23:55:11.109957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a6489f0a40e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_bak')
    op.add_column('user_group', sa.Column('user_group_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_group', 'user_group_name')
    op.create_table('task_bak',
    sa.Column('task_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('task_title', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('task_detail', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('deadline', mysql.DATETIME(), nullable=True),
    sa.Column('created', mysql.DATETIME(), nullable=True),
    sa.Column('updated', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('task_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
