"""empty message

Revision ID: 98b88c6fa8ec
Revises: 6a6489f0a40e
Create Date: 2019-01-12 23:38:29.723683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b88c6fa8ec'
down_revision = '6a6489f0a40e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_group', sa.Column('archived', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_group', 'archived')
    # ### end Alembic commands ###
