"""empty message

Revision ID: e5abdcf5a095
Revises: 98b88c6fa8ec
Create Date: 2019-01-14 22:31:06.458073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5abdcf5a095'
down_revision = '98b88c6fa8ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_group', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_group', 'is_archived')
    # ### end Alembic commands ###
